export const researchTreeNodes = Object.freeze([
  {
    id: "soil_mapping",
    category: "Farming Tech",
    name: "Soil Mapping",
    description: "Map micro-zones for healthier tree output.",
    costCash: 200,
    costResearchPoints: 0,
    unlockCondition: { type: "treesOwned", value: 3 },
    prerequisites: [],
    row: 0,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.2 }),
  },
  {
    id: "smart_irrigation",
    category: "Farming Tech",
    name: "Smart Irrigation",
    description: "Automate water cycles across orchards.",
    costCash: 900,
    costResearchPoints: 8,
    unlockCondition: { type: "cash", value: 800 },
    prerequisites: ["soil_mapping"],
    row: 1,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.32 }),
  },
  {
    id: "precision_pruning",
    category: "Farming Tech",
    name: "Precision Pruning",
    description: "Fine prune schedules improve fruit turnover.",
    costCash: 3200,
    costResearchPoints: 20,
    unlockCondition: { type: "treesOwned", value: 12 },
    prerequisites: ["smart_irrigation"],
    row: 2,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.45 }),
  },
  {
    id: "genetic_cultivars",
    category: "Farming Tech",
    name: "Genetic Cultivars",
    description: "Stabilize high-yield cultivars.",
    costCash: 14000,
    costResearchPoints: 60,
    unlockCondition: { type: "totalBananasEarned", value: 15000 },
    prerequisites: ["precision_pruning"],
    row: 3,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.7 }),
  },
  {
    id: "port_scheduling",
    category: "Logistics",
    name: "Port Scheduling",
    description: "Reduce bottlenecks in departure queues.",
    costCash: 650,
    costResearchPoints: 4,
    unlockCondition: { type: "totalBananasEarned", value: 700 },
    prerequisites: [],
    row: 0,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.1 }),
  },
  {
    id: "cold_chain",
    category: "Logistics",
    name: "Cold Chain Routing",
    description: "Maintain banana condition over distance.",
    costCash: 2800,
    costResearchPoints: 18,
    unlockCondition: { type: "cash", value: 2400 },
    prerequisites: ["port_scheduling"],
    row: 1,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.18 }),
  },
  {
    id: "dock_ai",
    category: "Logistics",
    name: "Dock AI",
    description: "Predict and reduce shipment cooldown windows.",
    costCash: 9000,
    costResearchPoints: 44,
    unlockCondition: { type: "treesOwned", value: 18 },
    prerequisites: ["cold_chain"],
    row: 2,
    col: 1,
    effect: (m) => ({ ...m, exportCooldownMultiplier: m.exportCooldownMultiplier * 0.86 }),
  },
  {
    id: "lane_optimizer",
    category: "Logistics",
    name: "Lane Optimizer",
    description: "Route cargo for maximum margin.",
    costCash: 28000,
    costResearchPoints: 95,
    unlockCondition: { type: "totalBananasEarned", value: 65000 },
    prerequisites: ["dock_ai"],
    row: 3,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.3 }),
  },
  {
    id: "hedge_desk",
    category: "Finance",
    name: "Hedge Desk",
    description: "Buffer volatility in banana commodity pricing.",
    costCash: 1800,
    costResearchPoints: 10,
    unlockCondition: { type: "cash", value: 1500 },
    prerequisites: [],
    row: 0,
    col: 2,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.08 }),
  },
  {
    id: "capital_efficiency",
    category: "Finance",
    name: "Capital Efficiency",
    description: "Improve capital turnover in operations.",
    costCash: 7500,
    costResearchPoints: 32,
    unlockCondition: { type: "totalBananasEarned", value: 12000 },
    prerequisites: ["hedge_desk"],
    row: 1,
    col: 2,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 1.35 }),
  },
  {
    id: "treasury_algorithms",
    category: "Finance",
    name: "Treasury Algorithms",
    description: "Automate high-frequency treasury decisions.",
    costCash: 26000,
    costResearchPoints: 85,
    unlockCondition: { type: "cash", value: 20000 },
    prerequisites: ["capital_efficiency"],
    row: 2,
    col: 2,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.22 }),
  },
  {
    id: "grip_gloves_mk2",
    category: "Weird Science",
    name: "Grip Gloves MK-II",
    description: "Nano-fibers dramatically increase pick speed.",
    costCash: 120,
    costResearchPoints: 3,
    unlockCondition: { type: "totalBananasEarned", value: 80 },
    prerequisites: [],
    row: 0,
    col: 3,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 1.45 }),
  },
  {
    id: "micro_drone_swarm",
    category: "Weird Science",
    name: "Micro-Drone Swarm",
    description: "Autonomous swarms support rapid harvest.",
    costCash: 9500,
    costResearchPoints: 40,
    unlockCondition: { type: "totalBananasEarned", value: 10000 },
    prerequisites: ["grip_gloves_mk2"],
    row: 1,
    col: 3,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 2.4 }),
  },
  {
    id: "quantum_pollination",
    category: "Weird Science",
    name: "Quantum Pollination",
    description: "Probability-locked bloom bursts.",
    costCash: 80000,
    costResearchPoints: 130,
    unlockCondition: { type: "cash", value: 70000 },
    prerequisites: ["micro_drone_swarm", "genetic_cultivars"],
    row: 2,
    col: 3,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 2.1 }),
  },
  {
    id: "reality_fork_finance",
    category: "Weird Science",
    name: "Reality Fork Finance",
    description: "Arbitrage outcomes across branching realities.",
    costCash: 160000,
    costResearchPoints: 250,
    unlockCondition: { type: "totalBananasEarned", value: 300000 },
    prerequisites: ["quantum_pollination", "treasury_algorithms"],
    row: 3,
    col: 3,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.5 }),
  },
]);

export const themedUpgradeNames = Object.freeze([
  "Banana Brand Synergy",
  "Executive Vine Analytics",
  "Monkey Middle Management",
  "Peel Profit Forecasting",
  "Jungle KPI Dashboard",
  "Boardroom Banana Split",
  "Chimp Compliance Office",
  "Merger & Acqui-banana",
  "Quarterly Peel Earnings",
  "Golden Bunch Branding",
  "Tailored Suit Tail Strategy",
  "Coconut Cost Accounting",
  "Primate Performance Reviews",
  "Banana Bond Issuance",
  "Guerrilla Guerrilla Marketing",
  "Monkey Macro Hedging",
  "Pulp Procurement Pipeline",
  "Plantation Portfolio Theory",
  "Vine-to-Market Optimization",
  "Swing Trading Division",
  "Bunch Benchmark Index",
  "Ape Asset Allocation",
  "Peel-to-Price Elasticity",
  "Banana Futures Command",
  "CFO Coconut Coffee",
  "Kingdom Expansion Deck",
  "Chairmonkey Signature Deal",
  "Prime Peel Partnerships",
  "Jungle Unicorn Initiative",
  "Infinite Banana Runway",
]);
