export const researchTreeNodes = Object.freeze([
  {
    id: "soil_mapping",
    category: "Farming Tech",
    name: "Soil Mapping",
    description: "Map micro-zones for healthier tree output.",
    summary: "Survey the grove so each tree grows under the right conditions.",
    effectText: "+20% production multiplier.",
    flavorText: "The first serious step from guesswork to agricultural control.",
    costCash: 200,
    costResearchPoints: 0,
    unlockCondition: { type: "treesOwned", value: 3 },
    prerequisites: [],
    row: 0,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.2 }),
  },
  {
    id: "smart_irrigation",
    category: "Farming Tech",
    name: "Smart Irrigation",
    description: "Automate water cycles across orchards.",
    summary: "Synchronize water delivery and stop wasting growth cycles.",
    effectText: "+32% production multiplier.",
    flavorText: "Roots like consistency more than heroics.",
    costCash: 900,
    costResearchPoints: 8,
    unlockCondition: { type: "cash", value: 800 },
    prerequisites: ["soil_mapping"],
    row: 1,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.32 }),
  },
  {
    id: "precision_pruning",
    category: "Farming Tech",
    name: "Precision Pruning",
    description: "Fine prune schedules improve fruit turnover.",
    summary: "Trim branches for faster, healthier fruit turnover.",
    effectText: "+45% production multiplier.",
    flavorText: "Cut less, but cut exactly where it matters.",
    costCash: 3200,
    costResearchPoints: 20,
    unlockCondition: { type: "treesOwned", value: 12 },
    prerequisites: ["smart_irrigation"],
    row: 2,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.45 }),
  },
  {
    id: "genetic_cultivars",
    category: "Farming Tech",
    name: "Genetic Cultivars",
    description: "Stabilize high-yield cultivars.",
    summary: "Lock in better genetics for stronger baseline harvests.",
    effectText: "+70% production multiplier.",
    flavorText: "Not every banana tree deserves to reproduce.",
    costCash: 14000,
    costResearchPoints: 60,
    unlockCondition: { type: "totalBananasEarned", value: 15000 },
    prerequisites: ["precision_pruning"],
    row: 3,
    col: 0,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 1.7 }),
  },
  {
    id: "port_scheduling",
    category: "Logistics",
    name: "Port Scheduling",
    description: "Reduce bottlenecks in departure queues.",
    summary: "Tighten departure timing so buyers pay for reliable flow.",
    effectText: "+10% export price multiplier.",
    flavorText: "A smooth dock is a profitable dock.",
    costCash: 650,
    costResearchPoints: 4,
    unlockCondition: { type: "totalBananasEarned", value: 700 },
    prerequisites: [],
    row: 0,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.1 }),
  },
  {
    id: "cold_chain",
    category: "Logistics",
    name: "Cold Chain Routing",
    description: "Maintain banana condition over distance.",
    summary: "Keep shipments fresh deep into the route network.",
    effectText: "+18% export price multiplier.",
    flavorText: "Bruised bananas are a tax on bad logistics.",
    costCash: 2800,
    costResearchPoints: 18,
    unlockCondition: { type: "cash", value: 2400 },
    prerequisites: ["port_scheduling"],
    row: 1,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.18 }),
  },
  {
    id: "dock_ai",
    category: "Logistics",
    name: "Dock AI",
    description: "Predict and reduce shipment cooldown windows.",
    summary: "Use predictive routing to reduce export downtime.",
    effectText: "14% faster export cooldowns.",
    flavorText: "The queue is only random until you model it properly.",
    costCash: 9000,
    costResearchPoints: 44,
    unlockCondition: { type: "treesOwned", value: 18 },
    prerequisites: ["cold_chain"],
    row: 2,
    col: 1,
    effect: (m) => ({ ...m, exportCooldownMultiplier: m.exportCooldownMultiplier * 0.86 }),
  },
  {
    id: "lane_optimizer",
    category: "Logistics",
    name: "Lane Optimizer",
    description: "Route cargo for maximum margin.",
    summary: "Route every shipment through the highest-value path.",
    effectText: "+30% export price multiplier.",
    flavorText: "Margin is just direction plus nerve.",
    costCash: 28000,
    costResearchPoints: 95,
    unlockCondition: { type: "totalBananasEarned", value: 65000 },
    prerequisites: ["dock_ai"],
    row: 3,
    col: 1,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.3 }),
  },
  {
    id: "hedge_desk",
    category: "Finance",
    name: "Hedge Desk",
    description: "Buffer volatility in banana commodity pricing.",
    summary: "Protect revenue against the market’s daily nonsense.",
    effectText: "+8% export price multiplier.",
    flavorText: "If the market moves, move before it does.",
    costCash: 1800,
    costResearchPoints: 10,
    unlockCondition: { type: "cash", value: 1500 },
    prerequisites: [],
    row: 0,
    col: 2,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.08 }),
  },
  {
    id: "capital_efficiency",
    category: "Finance",
    name: "Capital Efficiency",
    description: "Improve capital turnover in operations.",
    summary: "Free up working capital and turn every click into more value.",
    effectText: "+35% click multiplier.",
    flavorText: "Speed matters, but capital discipline matters longer.",
    costCash: 7500,
    costResearchPoints: 32,
    unlockCondition: { type: "totalBananasEarned", value: 12000 },
    prerequisites: ["hedge_desk"],
    row: 1,
    col: 2,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 1.35 }),
  },
  {
    id: "treasury_algorithms",
    category: "Finance",
    name: "Treasury Algorithms",
    description: "Automate high-frequency treasury decisions.",
    summary: "Let the treasury desk react faster than human operators can.",
    effectText: "+22% export price multiplier.",
    flavorText: "The spreadsheet has become self-aware.",
    costCash: 26000,
    costResearchPoints: 85,
    unlockCondition: { type: "cash", value: 20000 },
    prerequisites: ["capital_efficiency"],
    row: 2,
    col: 2,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.22 }),
  },
  {
    id: "grip_gloves_mk2",
    category: "Weird Science",
    name: "Grip Gloves MK-II",
    description: "Nano-fibers dramatically increase pick speed.",
    summary: "Upgrade your harvesting grip with ridiculous over-engineering.",
    effectText: "+45% click multiplier.",
    flavorText: "Science should never be subtle if it can be effective.",
    costCash: 120,
    costResearchPoints: 3,
    unlockCondition: { type: "totalBananasEarned", value: 80 },
    prerequisites: [],
    row: 0,
    col: 3,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 1.45 }),
  },
  {
    id: "micro_drone_swarm",
    category: "Weird Science",
    name: "Micro-Drone Swarm",
    description: "Autonomous swarms support rapid harvest.",
    summary: "Deploy support drones to amplify rapid manual harvesting.",
    effectText: "+140% click multiplier.",
    flavorText: "A swarm is just productivity with propellers.",
    costCash: 9500,
    costResearchPoints: 40,
    unlockCondition: { type: "totalBananasEarned", value: 10000 },
    prerequisites: ["grip_gloves_mk2"],
    row: 1,
    col: 3,
    effect: (m) => ({ ...m, clickMultiplier: m.clickMultiplier * 2.4 }),
  },
  {
    id: "quantum_pollination",
    category: "Weird Science",
    name: "Quantum Pollination",
    description: "Probability-locked bloom bursts.",
    summary: "Force high-probability bloom cycles into the orchard.",
    effectText: "+110% production multiplier.",
    flavorText: "Bloom timing is a suggestion until physics gets involved.",
    costCash: 80000,
    costResearchPoints: 130,
    unlockCondition: { type: "cash", value: 70000 },
    prerequisites: ["micro_drone_swarm", "genetic_cultivars"],
    row: 2,
    col: 3,
    effect: (m) => ({ ...m, productionMultiplier: m.productionMultiplier * 2.1 }),
  },
  {
    id: "reality_fork_finance",
    category: "Weird Science",
    name: "Reality Fork Finance",
    description: "Arbitrage outcomes across branching realities.",
    summary: "Exploit alternate financial outcomes for impossible margins.",
    effectText: "+50% export price multiplier.",
    flavorText: "If one timeline loses money, pick a better timeline.",
    costCash: 160000,
    costResearchPoints: 250,
    unlockCondition: { type: "totalBananasEarned", value: 300000 },
    prerequisites: ["quantum_pollination", "treasury_algorithms"],
    row: 3,
    col: 3,
    effect: (m) => ({ ...m, exportPriceMultiplier: m.exportPriceMultiplier * 1.5 }),
  },
  {
    id: "reactor_overclocking",
    category: "Weird Science",
    branch: "exotic",
    name: "Reactor Overclocking",
    description: "Push the Quantum Reactor beyond safe operational tolerances.",
    summary: "Increase Banana Matter throughput and push the exotic chain online faster.",
    effectText: "+65% Quantum Reactor output and +12% research point generation.",
    flavorText: "Safety margins are just lost throughput wearing a tie.",
    costCash: 220000,
    costResearchPoints: 320,
    unlockCondition: { type: "bananaMatter", value: 60 },
    prerequisites: ["quantum_pollination"],
    row: 0,
    col: 4,
    effect: (m) => ({
      ...m,
      reactorOutputMultiplier: m.reactorOutputMultiplier * 1.65,
      researchPointMultiplier: m.researchPointMultiplier * 1.12,
    }),
  },
  {
    id: "collider_refinement",
    category: "Weird Science",
    branch: "exotic",
    name: "Collider Refinement",
    description: "Tighten the Banana Matter collision envelope.",
    summary: "Improve Exotic Peel Particle extraction from every collider pass.",
    effectText: "+70% Collider output.",
    flavorText: "At this tier, precision is more valuable than caution.",
    costCash: 360000,
    costResearchPoints: 460,
    unlockCondition: { type: "colliderLevel", value: 1 },
    prerequisites: ["reactor_overclocking"],
    row: 1,
    col: 4,
    effect: (m) => ({
      ...m,
      colliderOutputMultiplier: m.colliderOutputMultiplier * 1.7,
    }),
  },
  {
    id: "containment_field_harmonics",
    category: "Weird Science",
    branch: "exotic",
    name: "Containment Field Harmonics",
    description: "Tune containment waves to preserve exotic output under load.",
    summary: "Convert Exotic Peel Particles into Antimatter Bananas more efficiently.",
    effectText: "+85% Containment output and +20% antimatter export scaling.",
    flavorText: "The field sings. The bananas survive. Usually.",
    costCash: 520000,
    costResearchPoints: 620,
    unlockCondition: { type: "containmentLevel", value: 1 },
    prerequisites: ["collider_refinement"],
    row: 2,
    col: 4,
    effect: (m) => ({
      ...m,
      containmentOutputMultiplier: m.containmentOutputMultiplier * 1.85,
      antimatterExportMultiplier: m.antimatterExportMultiplier * 1.2,
    }),
  },
  {
    id: "void_peel_stabilization",
    category: "Weird Science",
    branch: "exotic",
    name: "Void Peel Stabilization",
    description: "Stabilize antimatter peel structures before they collapse.",
    summary: "Turn every antimatter banana into a stronger export amplifier.",
    effectText: "+40% antimatter export scaling.",
    flavorText: "You cannot sell what reality refuses to hold together.",
    costCash: 410000,
    costResearchPoints: 520,
    unlockCondition: { type: "antimatterBananas", value: 8 },
    prerequisites: ["reactor_overclocking"],
    row: 0,
    col: 5,
    effect: (m) => ({
      ...m,
      antimatterExportMultiplier: m.antimatterExportMultiplier * 1.4,
    }),
  },
  {
    id: "singularity_bunches",
    category: "Weird Science",
    branch: "exotic",
    name: "Singularity Bunches",
    description: "Harvest clusters distorted by controlled singularity pressure.",
    summary: "Feed antimatter progress back into the core banana economy.",
    effectText: "+55% production multiplier and +18% click multiplier.",
    flavorText: "The fruit is denser. So are the margins.",
    costCash: 680000,
    costResearchPoints: 760,
    unlockCondition: { type: "antimatterBananas", value: 40 },
    prerequisites: ["void_peel_stabilization", "collider_refinement"],
    row: 1,
    col: 5,
    effect: (m) => ({
      ...m,
      productionMultiplier: m.productionMultiplier * 1.55,
      clickMultiplier: m.clickMultiplier * 1.18,
    }),
  },
  {
    id: "primate_cognition_archives",
    category: "Weird Science",
    branch: "exotic",
    name: "Primate Cognition Archives",
    description: "Store late-run intelligence as reusable prestige doctrine.",
    summary: "Convert exotic research into stronger prestige resets.",
    effectText: "+15% prestige gain from total bananas earned and +1 flat PIP on prestige.",
    flavorText: "If a run ends, the insight should not.",
    costCash: 900000,
    costResearchPoints: 980,
    unlockCondition: { type: "antimatterBananas", value: 120 },
    prerequisites: ["containment_field_harmonics"],
    row: 2,
    col: 5,
    effect: (m) => ({
      ...m,
      prestigeGainMultiplier: m.prestigeGainMultiplier * 1.15,
      prestigeFlatBonus: m.prestigeFlatBonus + 1,
    }),
  },
  {
    id: "recursive_executive_models",
    category: "Weird Science",
    branch: "exotic",
    name: "Recursive Executive Models",
    description: "Train management loops on successful prestige-era outcomes.",
    summary: "Push the reset loop harder without replacing it.",
    effectText: "+22% prestige gain, +1 flat PIP on prestige, and +18% research point generation.",
    flavorText: "The board now plans for the next universe before closing this one.",
    costCash: 1450000,
    costResearchPoints: 1400,
    unlockCondition: { type: "antimatterBananas", value: 320 },
    prerequisites: ["primate_cognition_archives", "singularity_bunches"],
    row: 3,
    col: 5,
    effect: (m) => ({
      ...m,
      prestigeGainMultiplier: m.prestigeGainMultiplier * 1.22,
      prestigeFlatBonus: m.prestigeFlatBonus + 1,
      researchPointMultiplier: m.researchPointMultiplier * 1.18,
    }),
  },
]);

export const themedUpgradeNames = Object.freeze([
  "Banana Brand Synergy",
  "Executive Vine Analytics",
  "Monkey Middle Management",
  "Peel Profit Forecasting",
  "Jungle KPI Dashboard",
  "Boardroom Banana Split",
  "Chimp Compliance Office",
  "Merger & Acqui-banana",
  "Quarterly Peel Earnings",
  "Golden Bunch Branding",
  "Tailored Suit Tail Strategy",
  "Coconut Cost Accounting",
  "Primate Performance Reviews",
  "Banana Bond Issuance",
  "Guerrilla Guerrilla Marketing",
  "Monkey Macro Hedging",
  "Pulp Procurement Pipeline",
  "Plantation Portfolio Theory",
  "Vine-to-Market Optimization",
  "Swing Trading Division",
  "Bunch Benchmark Index",
  "Ape Asset Allocation",
  "Peel-to-Price Elasticity",
  "Banana Futures Command",
  "CFO Coconut Coffee",
  "Kingdom Expansion Deck",
  "Chairmonkey Signature Deal",
  "Prime Peel Partnerships",
  "Jungle Unicorn Initiative",
  "Infinite Banana Runway",
]);
