export const farmEvolutions = Object.freeze([
  {
    id: "backyard_tree",
    name: "Backyard Tree",
    icon: "T1",
    baseBananasPerSecondPerTree: 0.2,
    harvest: { spawnIntervalMultiplier: 1, maxBananasBonus: 0, clickYieldMultiplier: 1, workerPickMultiplier: 1, goldenChanceAdd: 0, goldenMultiplierAdd: 0, shakeCooldownMultiplier: 1 },
    unlockCostCash: 0,
    quest: null,
    reward: { type: "none", description: "Starting setup" },
  },
  {
    id: "small_orchard",
    name: "Small Orchard",
    icon: "T2",
    baseBananasPerSecondPerTree: 0.45,
    harvest: { spawnIntervalMultiplier: 0.92, maxBananasBonus: 2, clickYieldMultiplier: 1.05, workerPickMultiplier: 1.08, goldenChanceAdd: 0, goldenMultiplierAdd: 0, shakeCooldownMultiplier: 0.95 },
    unlockCostCash: 150,
    quest: {
      id: "q_small_orchard",
      type: "trees_owned",
      target: 8,
      description: "Own 8 trees.",
    },
    reward: {
      type: "multiplier",
      value: 1.08,
      description: "+8% farm production multiplier",
    },
  },
  {
    id: "commercial_farm",
    name: "Commercial Farm",
    icon: "T3",
    baseBananasPerSecondPerTree: 1.1,
    harvest: { spawnIntervalMultiplier: 0.85, maxBananasBonus: 4, clickYieldMultiplier: 1.12, workerPickMultiplier: 1.16, goldenChanceAdd: 0.01, goldenMultiplierAdd: 2, shakeCooldownMultiplier: 0.9 },
    unlockCostCash: 600,
    quest: {
      id: "q_commercial_farm",
      type: "ship_to_buyer",
      buyerId: "raccoon_roadside",
      target: 250,
      description: "Ship 250 bananas to Raccoon Roadside Depot.",
    },
    reward: {
      type: "buyer",
      buyerId: "gorilla_wholesale",
      description: "Unlock buyer: Gorilla Wholesale Guild",
    },
  },
  {
    id: "mega_plantation",
    name: "Mega Plantation",
    icon: "T4",
    baseBananasPerSecondPerTree: 2.6,
    harvest: { spawnIntervalMultiplier: 0.77, maxBananasBonus: 6, clickYieldMultiplier: 1.2, workerPickMultiplier: 1.28, goldenChanceAdd: 0.02, goldenMultiplierAdd: 4, shakeCooldownMultiplier: 0.85 },
    unlockCostCash: 2500,
    quest: {
      id: "q_mega_plantation",
      type: "cash_earned",
      target: 8000,
      description: "Earn total cash of $8,000.",
    },
    reward: {
      type: "upgrade_category",
      category: "Export",
      description: "Unlock upgrade category: Export",
    },
  },
  {
    id: "tropical_bio_dome",
    name: "Tropical Bio-Dome",
    icon: "T5",
    baseBananasPerSecondPerTree: 6.2,
    harvest: { spawnIntervalMultiplier: 0.68, maxBananasBonus: 8, clickYieldMultiplier: 1.35, workerPickMultiplier: 1.45, goldenChanceAdd: 0.03, goldenMultiplierAdd: 6, shakeCooldownMultiplier: 0.8 },
    unlockCostCash: 10000,
    quest: {
      id: "q_tropical_bio_dome",
      type: "ship_to_buyer",
      buyerId: "penguin_freight",
      target: 1600,
      description: "Ship 1,600 bananas to Penguin Polar Freight.",
    },
    reward: {
      type: "multiplier",
      value: 1.12,
      description: "+12% farm production multiplier",
    },
  },
  {
    id: "quantum_banana_reactor",
    name: "Quantum Banana Reactor",
    icon: "T6",
    baseBananasPerSecondPerTree: 14.5,
    harvest: { spawnIntervalMultiplier: 0.6, maxBananasBonus: 10, clickYieldMultiplier: 1.55, workerPickMultiplier: 1.7, goldenChanceAdd: 0.05, goldenMultiplierAdd: 10, shakeCooldownMultiplier: 0.75 },
    unlockCostCash: 45000,
    quest: {
      id: "q_quantum_banana_reactor",
      type: "trees_owned",
      target: 90,
      description: "Own 90 trees.",
    },
    reward: {
      type: "upgrade_category",
      category: "Clicking",
      description: "Unlock upgrade category: Clicking",
    },
  },
  {
    id: "antimatter_banana_singularity",
    name: "Antimatter Banana Singularity",
    icon: "T7",
    baseBananasPerSecondPerTree: 35,
    harvest: { spawnIntervalMultiplier: 0.52, maxBananasBonus: 14, clickYieldMultiplier: 1.9, workerPickMultiplier: 2.1, goldenChanceAdd: 0.08, goldenMultiplierAdd: 18, shakeCooldownMultiplier: 0.7 },
    unlockCostCash: 200000,
    quest: {
      id: "q_antimatter_banana_singularity",
      type: "ship_to_buyer",
      buyerId: "shark_investment_group",
      target: 7500,
      description: "Ship 7,500 bananas to Shark Investment Group.",
    },
    reward: {
      type: "buyer",
      buyerId: "dragon_galactic_logistics",
      description: "Unlock buyer: Dragon Galactic Logistics",
    },
  },
]);
